const translations = {
  en: {
    headerTitle: 'ShannyBlog',
    headerHome: 'Home',
    headerNote: 'Note',
    headerProject: 'Project',
    headerTool: 'Tool',
    headerMedia: 'Media',
    headerBug: 'Bug',
    hederBoard: 'Board',
    headerAdmin: 'Admin',
    headerItemStudy: 'Study',
    headerItemWork: 'Work',
    headerItemLife: 'Life',
    headerItemWeb: 'Web',
    headerItemMobile: 'Mobile',
    headerItemGame: 'Game',
    headerItemCode: 'Code',
    headerItemBook: 'Book',
    headerItemPhoto: 'Photo',
    headerItemVideo: 'Video',
    headerItemMusic: 'Music',
    headerArticle: 'Article',
  },
  zh: {
    headerTitle: '珊的博客',
    headerHome: '首页',
    headerNote: '笔记',
    headerProject: '项目',
    headerTool: '工具',
    headerMedia: '媒体',
    headerBug: '问题',
    hederBoard: '论坛',
    headerAdmin: '管理',
    headerItemStudy: '学习',
    headerItemWork: '工作',
    headerItemLife: '生活',
    headerItemWeb: '网页端',
    headerItemMobile: '移动端',
    headerItemGame: '游戏',
    headerItemCode: '代码',
    headerItemBook: '书籍',
    headerItemPhoto: '照片',
    headerItemVideo: '视频',
    headerItemMusic: '音乐',
    headerArticle: '文章',
  },
}
export const translate = (key, isEnglish = false) => {
  const lang = isEnglish ? 'en' : 'zh'
  return translations[lang][key] || key
}
