server {
    server_name shanny.wang;
    return 301 https://www.shanny.wang$request_uri;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/shanny.wang/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shanny.wang/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    server_name  www.shanny.wang;

    location = /manage {
        return 301 /manage/;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

     location /manage/ {
        alias /project/shanny_blog/frontend/manage/dist/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location / {
        root /project/shanny_blog/frontend/blog/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/shanny.wang/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shanny.wang/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = shanny.wang) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name shanny.wang;
    return 404; # managed by Certbot


}
server {
    if ($host = www.shanny.wang) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen       80;
    server_name  www.shanny.wang;
    return 404; # managed by Certbot


}