import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faChevronDown,
  faMagnifyingGlass,
  faLanguage,
  faStar,
  faEarthAsia,
  faBell,
  faAward,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleLeft,
  faAngleRight,
  faTag,
  faUser,
  faClock,
  faRightFromBracket,
  faBarsProgress,
  faScrewdriverWrench,
  faPhotoFilm,
  faBug,
  faCircleInfo,
  faEnvelope,
  faNewspaper,
  faTags,
  faUsers,
  faNoteSticky,
  faList,
  faLayerGroup,
} from '@fortawesome/free-solid-svg-icons'
import {
  faCircle,
  faEdit,
  faCalendar,
  faCircleLeft,
} from '@fortawesome/free-regular-svg-icons'
import {
  faGithub,
  faSteam,
  faBilibili,
} from '@fortawesome/free-brands-svg-icons'
library.add(
  faCircle,
  faEdit,
  faGithub,
  faSteam,
  faBilibili,
  faBarsProgress,
  faChevronDown,
  faMagnifyingGlass,
  faLanguage,
  faStar,
  faEarthAsia,
  faCalendar,
  faBell,
  faAward,
  faAngleDoubleLeft,
  faAngleLeft,
  faRightFromBracket,
  faAngleRight,
  faAngleDoubleRight,
  faTag,
  faUser,
  faNewspaper,
  faClock,
  faScrewdriverWrench,
  faPhotoFilm,
  faBug,
  faEnvelope,
  faCircleInfo,
  faTags,
  faUsers,
  faNoteSticky,
  faList,
  faLayerGroup,
  faCircleLeft,
)
export { FontAwesomeIcon }
