spring:
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.shanny.controller

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 参数预览

shanny:
  jwt:
    user-secret-key: "shanny-blog&https://www.shanny.wang&ruanmengdashanny@gmail.com"
    user-ttl: 86400000
    user-token-name: "Authorization"