spring:
  datasource:
    blog:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/shanny_blog
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#knife4j配置
knife4j:
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: shanny
    password: 1234